parameters:
  initArgs:

steps:

- task: NuGetAuthenticate@1
  displayName: 🔏 Authenticate NuGet feeds
  inputs:
    ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
      nuGetServiceConnections: azure-public/msft_consumption
    forceReinstallCredentialProvider: true

# Authenticate if we're running on the azure-public account.
- ${{ if eq(variables['system.collectionId'], '63b6279a-d2f1-4bc3-a21c-db7614e92831') }}:
  - pwsh: |
      $PAT = '$(System.AccessToken)'
      $authFile = "npmRegistries:`n  //pkgs.dev.azure.com/azure-public/vside/_packaging/msft_consumption/npm/registry/:`n    npmAuthIdent: devdiv:$PAT`n    npmAlwaysAuth: true"
      $authFile
      Set-Content -Path $HOME/.yarnrc.yml -Value $authFile
    displayName: 🔏 Authenticate NPM registry
  - pwsh: |
      Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
      Write-Host "$env:SYSTEM_ACCESSTOKEN = $(System.AccessToken)"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - powershell: |
      Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
      Write-Host "$env:SYSTEM_ACCESSTOKEN = $(System.AccessToken)"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
- task: NodeTool@0
  inputs:
    versionSpec: 16.x
  displayName: ⚙️ Install Node.js

- script: corepack enable
  displayName: ⚙️ Install yarn

- powershell: |
    $AccessToken = '$(System.AccessToken)' # Avoid specifying the access token directly on the init.ps1 command line to avoid it showing up in errors
    .\init.ps1 -AccessToken $AccessToken ${{ parameters['initArgs'] }} -UpgradePrerequisites -NoNuGetCredProvider
    dotnet --info

    # Print mono version if it is present.
    if (Get-Command mono -ErrorAction SilentlyContinue) {
      mono --version
    }
  displayName: ⚙ Install prerequisites

- powershell: azure-pipelines/variables/_pipelines.ps1
  failOnStderr: true
  displayName: ⚙ Set pipeline variables based on source
  name: SetPipelineVariables
